name: NET

on:
  push:
    branches: [ Dotnet_4.6 ]
  pull_request:
    branches: [ Dotnet_4.6 ]

jobs:
  build:
    runs-on: windows-lastest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET46
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe "$Env:GITHUB_WORKSPACE\DayZ cleaner.sln"
